version: "3.8"

services:
  duckling-nuxt:
    environment:
      - NUXT_PUBLIC_BACKEND_URL=${NUXT_PUBLIC_BACKEND_URL}
      - NUXT_PUBLIC_WEB_PLAYER_URL=${NUXT_PUBLIC_WEB_PLAYER_URL}
      - NUXT_QUICKPAY_API_KEY=${NUXT_QUICKPAY_API_KEY}
      - NUXT_CAMPAIGN_DB_URL=${NUXT_CAMPAIGN_DB_URL}
      - NUXT_CAMPAIGN_DB_USERNAME=${NUXT_CAMPAIGN_DB_USERNAME}
      - NUXT_CAMPAIGN_DB_PASSWORD=${NUXT_CAMPAIGN_DB_PASSWORD}
      - NUXT_CAMPAIGN_DB_NAMESPACE=${NUXT_CAMPAIGN_DB_NAMESPACE}
      - NUXT_CAMPAIGN_DB_DATABASE=${NUXT_CAMPAIGN_DB_DATABASE}
    image: duckling-nuxt
    container_name: duckling-nuxt
    build:
      context: .
      dockerfile: dockerfile.nuxt
    ports:
      - "3000:3000"
    networks:
      - duckling-net

  nginx:
    image: duckling-nginx
    container_name: duckling-nginx
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/web.duckling.co/fullchain.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      - /etc/letsencrypt/live/web.duckling.co/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
    depends_on:
      - duckling-nuxt
    networks:
      - duckling-net

networks:
  duckling-net:
    driver: bridge
