# Build stage
# Production stage
FROM nginx:stable-alpine

# Copy Nginx configuration file into place
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose ports 80 and 443
EXPOSE 80 443

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]