name: Build and deploy the docker images

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run-images:
    runs-on: self-hosted
    env:
      NUXT_PUBLIC_BACKEND_URL: ${{secrets.NUXT_PUBLIC_BACKEND_URL}}
      NUXT_PUBLIC_WEB_PLAYER_URL: ${{secrets.NUXT_PUBLIC_WEB_PLAYER_URL}}
      NUXT_QUICKPAY_API_KEY: ${{secrets.NUXT_QUICKPAY_API_KEY}}
      NUXT_CAMPAIGN_DB_URL: ${{secrets.NUXT_CAMPAIGN_DB_URL}}
      NUXT_CAMPAIGN_DB_USERNAME: ${{secrets.NUXT_CAMPAIGN_DB_USERNAME}}
      NUXT_CAMPAIGN_DB_PASSWORD: ${{secrets.NUXT_CAMPAIGN_DB_PASSWORD}}
      NUXT_CAMPAIGN_DB_NAMESPACE: ${{secrets.NUXT_CAMPAIGN_DB_NAMESPACE}}
      NUXT_CAMPAIGN_DB_DATABASE: ${{secrets.NUXT_CAMPAIGN_DB_DATABASE}}
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.ACTIONS_DEPLOY_KEY}}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ducklingco/duckling-web
          ssh-key: ${{secrets.ACTIONS_DEPLOY_KEY}}
      - name: Build images
        run: docker-compose build
      - name: Stop specific containers
        run: |
          containers=$(docker ps -aq -f name=duckling-nginx -f name=duckling-nuxt)
          if [ -n "$containers" ]; then
            docker stop $containers
          fi
      - name: Removes nuxt container
        run: |
          if [[ $(docker ps -aq -f name=duckling-nuxt) ]]; then
            docker rm $(docker ps -aq -f name=duckling-nuxt)
          fi
      - name: Removes nginx container
        run: |
          if [[ $(docker ps -aq -f name=duckling-nginx) ]]; then
            docker rm $(docker ps -aq -f name=duckling-nginx)
          fi
      - name: Run new containers
        run: docker-compose up -d
