name: Build and deploy the docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-images:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build images
        run: docker-compose build
      - name: Stop specific containers
        run: docker stop $(docker ps -aq -f name=duckling-nginx -f name=duckling-nuxt)
      - name: Removes nuxt container
        run: docker rm $(docker ps -aq -f name=duckling-nuxt)
      - name: Removes nginx container
        run: docker rm $(docker ps -aq -f name=duckling-nginx)
      - name: Run new containers
        run: docker-compose up -d
